name: Docker Image CI

on:
  push:
    branches: [ master, f-test, f-apline ]
  pull_request:
    branches: [ master, f-test, f-apline ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      OPENSSL_VERSION: 1.0.2u
      OPENSSL_FLAVOR: -vuln1
    steps:
    - uses: actions/checkout@v2
    - name: Build the OpenSSL Docker image
      run: docker build --build-arg OPENSSL_VERSION=1.0.2u -t yurkao/openssl-alpine:1.0.2u-vuln openssl-apline
    - name: Build the Python Docker image
      run: docker build --build-arg OPENSSL_VERSION=1.0.2u-vuln -t yurkao/python:3.9.6-1.0.2u-vuln python-apline
    - name: Build the NGINX Docker image
      run: docker build --build-arg OPENSSL_VERSION=1.0.2u-vuln -t yurkao/nginx:1.0.2u-vuln nginx

