name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      uses: docker/login-action@v2
      with:
        registry: yurkao
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_ACCESS }}

    - name: Build OpenSSL
      uses: docker/build-push-action@v2
      with:
        context: openssl
        push: true
        build-args: |
          OPENSSL_VERSION=1.0.2u
        tags: yurkao/openssl:1.0.2u-vuln

    - name: Build Python
      uses: docker/build-push-action@v2
      with:
        context: python
        push: true
        build-args: |
          OPENSSL_VERSION=1.0.2u-vuln
        tags: yurkao/python:1.0.2u-vuln

    - name: Build NGINX
      uses: docker/build-push-action@v2
      with:
        context: nginx
        push: true
        build-args: |
          OPENSSL_VERSION=1.0.2u-vuln
        tags: yurkao/nginx:1.0.2u-vuln
